---
- name: "Install elixir packages"
  apt: name="{{ item }}={{ elixir.version }}" state=present
  with_items: "{{ elixir.packages }}"
  become: yes

- name: "Install elixir hex"
  command: bash -lc "mix local.hex --force"
  become: yes
  become_user: "{{ ansible_user }}"

- name: "Install elixir rebar"
  command: bash -lc "mix local.rebar --force"
  become: yes
  become_user: "{{ ansible_user }}"
